### ISSUE TITLE
Error docker run

### ISSUE THREAD

**Issue by Classsic** [fschuindt/docker-smb#1]
Hi, I get this error:
`smbd version 4.8.11 started.
Copyright Andrew Tridgell and the Samba Team 1992-2018
INFO: Current debug levels:
  all: 10
  tdb: 10
  printdrivers: 10
  lanman: 10
  smb: 10
  rpc_parse: 10
  rpc_srv: 10
  rpc_cli: 10
  passdb: 10
  sam: 10
  auth: 10
  winbind: 10
  vfs: 10
  idmap: 10
  quota: 10
  acls: 10
  locking: 10
  msdfs: 10
  dmapi: 10
  registry: 10
  scavenger: 10
  dns: 10
  ldb: 10
  tevent: 10
  auth_audit: 10
  auth_json_audit: 10
  kerberos: 10
  drs_repl: 10
  smb2: 10
  smb2_credits: 10
pm_process() returned Yes
lp_servicenumber: couldn't find homes
get_current_groups: user is in 11 groups: 0, 1, 2, 3, 4, 6, 10, 11, 20, 26, 27
messaging_dgm_ref: messaging_dgm_init returned No error information
messaging_dgm_ref: unique = 7095483267913711634
Registering messaging pointer for type 2 - private_data=0
Registering messaging pointer for type 9 - private_data=0
Registered MSG_REQ_POOL_USAGE
Registering messaging pointer for type 11 - private_data=0
Registering messaging pointer for type 12 - private_data=0
Registered MSG_REQ_DMALLOC_MARK and LOG_CHANGED
Registering messaging pointer for type 1 - private_data=0
Registering messaging pointer for type 5 - private_data=0
Registering messaging pointer for type 51 - private_data=0
messaging_init_internal: my id: 1
lp_load_ex: refreshing parameters
Freeing parametrics:
Initialising global parameters
Processing section "[global]"
doing parameter map to guest = Bad User
doing parameter log file = /var/log/samba/%m
doing parameter log level = 10
INFO: Current debug levels:
  all: 10
  tdb: 10
  printdrivers: 10
  lanman: 10
  smb: 10
  rpc_parse: 10
  rpc_srv: 10
  rpc_cli: 10
  passdb: 10
  sam: 10
  auth: 10
  winbind: 10
  vfs: 10
  idmap: 10
  quota: 10
  acls: 10
  locking: 10
  msdfs: 10
  dmapi: 10
  registry: 10
  scavenger: 10
  dns: 10
  ldb: 10
  tevent: 10
  auth_audit: 10
  auth_json_audit: 10
  kerberos: 10
  drs_repl: 10
  smb2: 10
  smb2_credits: 10
Processing section "[guest]"
add_a_service: Creating snum = 0 for guest
hash_a_service: creating servicehash
hash_a_service: hashing index 0 for service name guest
doing parameter path = /Shared/
doing parameter read only = no
doing parameter guest ok = yes
pm_process() returned Yes
lp_servicenumber: couldn't find homes
add_a_service: Creating snum = 1 for IPC$
hash_a_service: hashing index 1 for service name IPC$
adding IPC service
lp_file_list_changed()
file /etc/samba/smb.conf -> /etc/samba/smb.conf  last mod_time: Thu May 23 13:26:53 2019

added interface eth0 ip=172.17.0.3 bcast=172.17.255.255 netmask=255.255.0.0
loaded services
Netbios name list:-
my_netbios_names[0]="63A078214E36"
INFO: Profiling support unavailable in this build.
Standard input is not a socket, assuming -D option
Becoming a daemon.
exit_daemon: daemon failed to start: Failed to create session, error code 1
`
What i´m missing?
thanks.

**Comment by pmungenast** [comment]
Hi, got the same issue today. I could work around it by setting the version of the Alpine base image to 3.7 instead of latest (e.g. "FROM alpine:3.7"). Not the optimal solution, but works for the moment.

**Comment by andrusstrockiy** [comment]
@pmungenast  thanks for your workaround
