### ISSUE TITLE
Error Docker-compose build

### ISSUE THREAD

**Issue by DDT88** [fschuindt/docker-smb#4]
hi, 

when i run docker-compose build,I received this error

**WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz: IO ERROR
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/community/x86_64/APKINDEX.tar.gz
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.7/community/x86_64/APKINDEX.tar.gz: IO ERROR
ERROR: unsatisfiable constraints:
  samba-client (missing):
    required by: world[samba-client]
  samba-common-tools (missing):
    required by: world[samba-common-tools]
  samba-server (missing):
    required by: world[samba-server]
The command '/bin/sh -c apk add --no-cache --update     samba-common-tools     samba-client     samba-server' returned a non-zero code: 3
ERROR: Service 'samba' failed to build**

Where is the problem ? 
Thanks for support

**Comment by sedataktas** [comment]
restart docker service
